services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: roomie
      MONGO_INITDB_ROOT_PASSWORD: roomie

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: roomie
      ME_CONFIG_MONGODB_ADMINPASSWORD: roomie
      ME_CONFIG_MONGODB_SERVER: mongodb

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices-net:
    driver: bridge

volumes:
  mongodb: