spring:
  application:
    name: household-service
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/${keycloak.realm}

keycloak:
  realm: roomie_app